export type AbcmErrorCode =
  | "AUTHENTICATION_REQUIRED"
  | "REQUEST_INVALID"
  | "ACCESS_DENIED"
  | "PROJECT_ANCHOR_NOT_RESOLVED"
  | "DOMAIN_LANGUAGE_CONFIGURATION_INVALID"
  | "PROJECT_LANGUAGE_CONFIGURATION_INVALID"
  | "DOMAIN_LANGUAGE_BOOTSTRAP_REQUIRED"
  | "DOMAIN_LANGUAGE_BOOTSTRAP_STALE"
  | "UNKNOWN_DOMAIN"
  | "UNKNOWN_DOMAIN_TERM"
  | "AMBIGUOUS_DOMAIN_TERM"
  | "TARGET_SCOPE_AMBIGUOUS"
  | "TARGET_SCOPE_INVALID"
  | "PATH_RESOLUTION_NOT_CONVERGED"
  | "CONTEXT_CONFIGURATION_INVALID"
  | "CONTEXT_FINGERPRINT_CONFLICT"
  | "CONTEXT_FINGERPRINT_NOT_FOUND"
  | "CONTEXT_OUTCOME_CONFLICT"
  | "ACCEPTED_ARTIFACT_IMMUTABLE"
  | "CONTEXT_CONFLICT_REQUIRES_OPERATOR"
  | "REQUIRED_CONTEXT_EXCEEDS_LIMIT"
  | "REQUIRED_CONTEXT_ACCESS_DENIED"
  | "SKILL_CONNECTION_AMBIGUOUS"
  | "REQUIRED_SKILL_LINK_UNRESOLVED"
  | "GLOBAL_SKILL_MUST_BE_WORKFLOW_OWNED"
  | "WORKSPACE_NOT_FOUND"
  | "WORKSPACE_ALREADY_EXISTS"
  | "WORKSPACE_REGISTRATION_DISABLED"
  | "SCAN_LEASE_BUSY"
  | "SCAN_FENCING_STALE"
  | "DERIVED_STORE_CORRUPT"
  | "DERIVED_STORE_OWNER_BUSY"
  | "DERIVED_STORE_OWNER_LOST"
  | "FILE_PATH_INVALID"
  | "FILE_PATH_FORBIDDEN"
  | "FILE_NOT_FOUND"
  | "FILE_ALREADY_EXISTS"
  | "FILE_CHECKSUM_MISMATCH"
  | "FILE_TOO_LARGE"
  | "FILE_TYPE_UNSUPPORTED"
  | "UPLOAD_NOT_FOUND"
  | "UPLOAD_EXPIRED"
  | "UPLOAD_TOO_LARGE"
  | "UPLOAD_CHUNK_INVALID"
  | "UPLOAD_CHUNK_CONFLICT"
  | "UPLOAD_CHECKSUM_MISMATCH"
  | "UPLOAD_INCOMPLETE"
  | "UPLOAD_STATE_INVALID"
  | "BATCH_TOO_LARGE"
  | "BATCH_REVISION_MISMATCH"
  | "BATCH_IDEMPOTENCY_CONFLICT"
  | "BATCH_RECOVERY_REQUIRED"
  | "SYNC_CURSOR_INVALID"
  | "SYNC_CURSOR_EXPIRED"
  | "SYNC_IDEMPOTENCY_CONFLICT"
  | "SYNC_OBJECT_NOT_FOUND"
  | "SYNC_OBJECT_CONFLICT"
  | "SYNC_JOURNAL_CORRUPT"
  | "DOCUMENTATION_SYNC_DISABLED"
  | "SOURCE_CONNECTOR_UNAVAILABLE"
  | "SOURCE_TARGET_CONFLICT"
  | "DOCUMENTATION_MAPPING_AMBIGUOUS"
  | "DOCUMENTATION_IMPORT_NOT_FOUND"
  | "DOCUMENTATION_IMPORT_STALE"
  | "DOCUMENTATION_SOURCE_ALREADY_MANAGED"
  | "DOCUMENTATION_RECOVERY_REQUIRED"
  | "CUTOVER_APPROVAL_REQUIRED"
  | "CUTOVER_CHECKSUM_MISMATCH"
  | "MIRROR_DOCUMENT_READ_ONLY"
  | "RESOURCE_NOT_FOUND"
  | "RESOURCE_STALE"
  | "MCP_CURSOR_INVALID"
  | "MCP_OPERATION_CANCELLED"
  | "MCP_OPERATION_TIMEOUT"
  | "REST_RATE_LIMIT_EXCEEDED"
  | "REST_REQUEST_CANCELLED"
  | "REST_REQUEST_TIMEOUT"
  | "MAP_NOT_BUILT"
  | "SCOPE_MANIFEST_INVALID"
  | "WORKSPACE_ROOT_MUST_BE_WORKFLOW";

const HTTP_STATUS_BY_CODE: Record<AbcmErrorCode, number> = {
  AUTHENTICATION_REQUIRED: 401,
  REQUEST_INVALID: 400,
  ACCESS_DENIED: 403,
  PROJECT_ANCHOR_NOT_RESOLVED: 404,
  DOMAIN_LANGUAGE_CONFIGURATION_INVALID: 422,
  PROJECT_LANGUAGE_CONFIGURATION_INVALID: 422,
  DOMAIN_LANGUAGE_BOOTSTRAP_REQUIRED: 400,
  DOMAIN_LANGUAGE_BOOTSTRAP_STALE: 409,
  UNKNOWN_DOMAIN: 422,
  UNKNOWN_DOMAIN_TERM: 422,
  AMBIGUOUS_DOMAIN_TERM: 409,
  TARGET_SCOPE_AMBIGUOUS: 409,
  TARGET_SCOPE_INVALID: 422,
  PATH_RESOLUTION_NOT_CONVERGED: 409,
  CONTEXT_CONFIGURATION_INVALID: 422,
  CONTEXT_FINGERPRINT_CONFLICT: 409,
  CONTEXT_FINGERPRINT_NOT_FOUND: 404,
  CONTEXT_OUTCOME_CONFLICT: 409,
  ACCEPTED_ARTIFACT_IMMUTABLE: 409,
  CONTEXT_CONFLICT_REQUIRES_OPERATOR: 409,
  REQUIRED_CONTEXT_EXCEEDS_LIMIT: 413,
  REQUIRED_CONTEXT_ACCESS_DENIED: 403,
  SKILL_CONNECTION_AMBIGUOUS: 409,
  REQUIRED_SKILL_LINK_UNRESOLVED: 422,
  GLOBAL_SKILL_MUST_BE_WORKFLOW_OWNED: 422,
  WORKSPACE_NOT_FOUND: 404,
  WORKSPACE_ALREADY_EXISTS: 409,
  WORKSPACE_REGISTRATION_DISABLED: 503,
  SCAN_LEASE_BUSY: 409,
  SCAN_FENCING_STALE: 409,
  DERIVED_STORE_CORRUPT: 500,
  DERIVED_STORE_OWNER_BUSY: 409,
  DERIVED_STORE_OWNER_LOST: 409,
  FILE_PATH_INVALID: 400,
  FILE_PATH_FORBIDDEN: 403,
  FILE_NOT_FOUND: 404,
  FILE_ALREADY_EXISTS: 409,
  FILE_CHECKSUM_MISMATCH: 412,
  FILE_TOO_LARGE: 413,
  FILE_TYPE_UNSUPPORTED: 415,
  UPLOAD_NOT_FOUND: 404,
  UPLOAD_EXPIRED: 410,
  UPLOAD_TOO_LARGE: 413,
  UPLOAD_CHUNK_INVALID: 400,
  UPLOAD_CHUNK_CONFLICT: 409,
  UPLOAD_CHECKSUM_MISMATCH: 412,
  UPLOAD_INCOMPLETE: 409,
  UPLOAD_STATE_INVALID: 500,
  BATCH_TOO_LARGE: 413,
  BATCH_REVISION_MISMATCH: 409,
  BATCH_IDEMPOTENCY_CONFLICT: 409,
  BATCH_RECOVERY_REQUIRED: 500,
  SYNC_CURSOR_INVALID: 400,
  SYNC_CURSOR_EXPIRED: 409,
  SYNC_IDEMPOTENCY_CONFLICT: 409,
  SYNC_OBJECT_NOT_FOUND: 404,
  SYNC_OBJECT_CONFLICT: 409,
  SYNC_JOURNAL_CORRUPT: 500,
  DOCUMENTATION_SYNC_DISABLED: 503,
  SOURCE_CONNECTOR_UNAVAILABLE: 503,
  SOURCE_TARGET_CONFLICT: 409,
  DOCUMENTATION_MAPPING_AMBIGUOUS: 409,
  DOCUMENTATION_IMPORT_NOT_FOUND: 404,
  DOCUMENTATION_IMPORT_STALE: 409,
  DOCUMENTATION_SOURCE_ALREADY_MANAGED: 409,
  DOCUMENTATION_RECOVERY_REQUIRED: 409,
  CUTOVER_APPROVAL_REQUIRED: 403,
  CUTOVER_CHECKSUM_MISMATCH: 409,
  MIRROR_DOCUMENT_READ_ONLY: 409,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_STALE: 409,
  MCP_CURSOR_INVALID: 400,
  MCP_OPERATION_CANCELLED: 499,
  MCP_OPERATION_TIMEOUT: 504,
  REST_RATE_LIMIT_EXCEEDED: 429,
  REST_REQUEST_CANCELLED: 499,
  REST_REQUEST_TIMEOUT: 504,
  MAP_NOT_BUILT: 409,
  SCOPE_MANIFEST_INVALID: 422,
  WORKSPACE_ROOT_MUST_BE_WORKFLOW: 422,
};

export class AbcmError extends Error {
  readonly code: AbcmErrorCode;
  readonly status: number;
  readonly details?: Readonly<Record<string, unknown>>;

  constructor(code: AbcmErrorCode, message: string, details?: Readonly<Record<string, unknown>>) {
    super(message);
    this.name = "AbcmError";
    this.code = code;
    this.status = HTTP_STATUS_BY_CODE[code];
    if (details !== undefined) this.details = details;
  }
}
